# DEVELOPPEMENT
version: '3.1'

services:
  nodejs:
    build:
      context: ./
      dockerfile: Node/Dockerfile
    ports:
      - "4040:4040"
    depends_on:
      - postgres
      - redis
    container_name: nodeapi
    hostname: nodeapi
    environment:
      - NODE_ENV=development
      - API_PORT=4040
      - DB_HOST=postgres  # Container name
      - DB_PORT=5432      # Default port : 5432
      - DB_NAME=database
      - DB_USER=admin
      - DB_PASSWORD=admin
      - REDIS_HOST=redis  # Container name
    volumes:
      - ./:/home/node/app
    restart: unless-stopped
    networks:
      - network-db

  postgres:
    image: postgres:alpine
    depends_on:
      - redis
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
      PGDATA: /tmp
    restart: unless-stopped
    volumes:
      - ./postgres-persistant-data:/data/postgres
    networks:
      - network-db

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--bind", "redis", "--port", "6379"]

networks:
  network-db: