version: 2.1
executors:
  mypublisher:
    environment:
      PROJECT_NAME: devops-team-1
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build:
    executor: mypublisher
    steps:
      - checkout
      - setup_remote_docker # Ask circleci new Docker Engine to build outside of container
      - run:
          name: Build Docker images (docker-compose)
          command: docker-compose -f ./docker-compose.dev.yaml build --compress --force-rm --no-cache --pull --parallel
      - run:
          name: Archive nodejs Docker image
          command: docker save -o ./${PROJECT_NAME}_nodejs.tar project_nodejs
      - persist_to_workspace:
          root: .
          paths:
            - ./*.tar
  publish-latest:
    executor: mypublisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived nodejs image
          command: docker load -i /tmp/workspace/${PROJECT_NAME}_nodejs.tar
      - run:
          name: Rename nodejs image
          command: docker tag project_nodejs ced23/${PROJECT_NAME}_node:latest
      - run:
          name: Publish Node Image to Docker Hub
          command: |
            echo $PSW | base64 --decode | docker login -u $USER --password-stdin
            docker push ced23/${PROJECT_NAME}_node:latest

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
