version: 2.1
executors:
  mypublisher:
    environment:
      PROJECT_NAME: devops-tp2-team-1
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build-images:
    executor: mypublisher
    steps:
      - checkout
      - setup_remote_docker # Ask circleci new Docker Engine to build outside of container
      - run:
          name: Build Docker images (docker-compose)
          command: docker-compose -f ./docker-compose.dev.yaml up --build --force-recreate # docker-compose -f ./docker-compose.dev.yml build --compress --force-rm --no-cache --pull --parallel
      - run:
          name: Archive nodejs Docker image
          command: docker save -o ./${PROJECT_NAME}_nodejs.tar docker_nodejs
      - run:
          name: Archive nginx Docker image
          command: docker save -o ./${PROJECT_NAME}_nginx.tar docker_nginx
      - persist_to_workspace:
          root: .
          paths:
            - ./*.tar
  publish-latest:
    executor: mypublisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived nodejs Docker image
          command: docker load -i /tmp/workspace/${PROJECT_NAME}_nodejs.tar
      - run:
          name: Load archived nginx Docker image
          command: docker load -i /tmp/workspace/${PROJECT_NAME}_nginx.tar
      - run:
          name: Rename nginx Docker image
          command: docker tag docker_nginx Ced23/${PROJECT_NAME}_nginx:latest
      - run:
          name: Rename nodejs Docker image
          command: docker tag docker_nodejs Ced23/${PROJECT_NAME}_node:latest
      - run:
          name: Publish Nginx Image to Docker Hub
          command: |
            echo $PSW | base64 --decode | docker login -u $USER --password-stdin
            docker push Ced23/${PROJECT_NAME}_nginx:latest
      - run:
          name: Publish Node Image to Docker Hub
          command: |
            echo $PSW | base64 --decode | docker login -u $USER --password-stdin
            docker push Ced23/${PROJECT_NAME}_node:latest

workflows:
  version: 2
  build-master:
    jobs:
      - build-images:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build-images
          filters:
            branches:
              only: master
